### ISSUE TITLE
d01/ex02 Init vector with tuple is not (longer) asked

### ISSUE THREAD

**Issue by mli42** [42-AI/Python-Bootcamp-Corrections#6]
Day : 01
Ex   : 02

The test `print(Vector((10, 12)).values)` raise an error as it is not a range \
This should be `print(Vector(range(10, 12)).values)`

It is asked to handle such error `print(Vector((3, 1)).values)` but it is not a range + `range(3,1)` is empty, this test has no sense now

This test should use a range as well
```py
v = Vector((1, 1))
print(v.values)
```

We can't create a `range(4, 7.1)` either + it has extra characters:
```
Vector((4, 7.1)) `:
```
This case can be tested by `Vector(7.1)`

**Comment by qfeuilla** [comment]
in the subject it is specified like this : 
```
a range: Vector((10,16)) -> the vector will have values = [[10.0], [11.0],
[12.0], [13.0], [14.0], [15.0]]
```
so the vector can be initialized with a tuple
